apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
#   namespace: argocd
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
#     namespace: argocd
    namespace: default
  project: default
  source:
    path: charts/argocd
    repoURL: https://github.com/mikecbone/argo-example.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
