apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-mongodb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: MongoDB

  sourceRepos:
    - "*"

  destinations:
    - namespace: mongodb
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace

  namespaceResourceBlacklist:
    - group: ""
      kind: ResourceQuota
    - group: ""
      kind: LimitRange
    - group: ""
      kind: NetworkPolicy

  orphanedResources:
    warn: false
